language: cpp

compiler:
    - clang++

addons:
    apt:
        packages:
            - cmake
            - clang-format

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test
    - cd $TRAVIS_BUILD_DIR && ./tools/clang-format.sh
