#!/bin/bash
set -u

# Redirect output to stderr.
exec 1>&2

# Accumulate error code
ret_val=0

top_dir=$(git rev-parse --show-toplevel)
tools_dir="${top_dir}/tools"

bash ${tools_dir}/clang-format.sh
ret_val=$(($ret_val+$?))

exit $ret_val
